In [1]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [3]:
#Inspection and Properties
print("Shape:", temperatures_w1.shape)
print("Data type:", temperatures_w1.dtype)
print("Number of elements:", temperatures_w1.size)


Shape: (7,)
Data type: float64
Number of elements: 7


In [4]:
#Array Operations

#Convert Celsius → Fahrenheit:

temperatures_f = (temperatures_w1 * 9/5) + 32
print("Fahrenheit:", temperatures_f)


Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [5]:
#Find statistics:

print("Max:", np.max(temperatures_w1))
print("Min:", np.min(temperatures_w1))
print("Mean:", np.mean(temperatures_w1))


Max: 26.1
Min: 20.8
Mean: 23.542857142857144


In [6]:
#Array Slicing and Indexing
# First three days
print("First 3 days:", temperatures_w1[:3])

# Weekend (last two days)
print("Weekend:", temperatures_w1[-2:])

# Middle three days (index 2,3,4)
print("Middle 3 days:", temperatures_w1[2:5])


First 3 days: [22.5 25.3 20.8]
Weekend: [24.8 21.9]
Middle 3 days: [20.8 23.4 26.1]


In [7]:
#Create a 2D Array

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Week 2
])
print(temperatures)


[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [8]:
#Pandas Series
#1. Creating Pandas Series
import pandas as pd

marks = pd.Series([95, 92, 89, 85, 80],
                  index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)




Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [9]:
#2. Indexing and Slicing
# a. Integer index position (1st rank student → index 0)
print("1st rank mark:", marks[0])

# b. loc accessor (top 3 ranks by labels)
print("Top 3 ranks (loc):")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

# c. iloc accessor (3rd rank student → index 2)
print("3rd rank mark (iloc):", marks.iloc[2])

# d. Boolean mask (marks > 90)
print("Marks > 90:")
print(marks[marks > 90])


1st rank mark: 95
Top 3 ranks (loc):
Rank1    95
Rank2    92
Rank3    89
dtype: int64
3rd rank mark (iloc): 89
Marks > 90:
Rank1    95
Rank2    92
dtype: int64


/tmp/ipykernel_1103/1828132925.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("1st rank mark:", marks[0])


In [10]:
#3. Manipulating Series
# a. Modify 1st rank mark to 100
marks['Rank1'] = 100
print("Updated marks:\n", marks)

# b. Remove last rank entry
marks = marks.drop('Rank5')
print("After removing last rank:\n", marks)

# c. Compute CGPA (marks ÷ 10)
cgpa = marks / 10
print("CGPA:\n", cgpa)


Updated marks:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
After removing last rank:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
CGPA:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [13]:
# Pandas DataFrame

import pandas as pd

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
                        'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East',
               'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [14]:
#2. Data Exploration
# Display DataFrame
print(transactions)

# Basic info
print(transactions.head())       # First 5 rows
print(transactions.tail())       # Last 5 rows
print("Shape:", transactions.shape)
print("Columns:", transactions.columns)
print("Data types:\n", transactions.dtypes)

# Display specific columns
print(transactions[['ProductCategory', 'Amount']])

# Retrieve last 3 columns
print(transactions.iloc[:, -3:])   # Using iloc

# Filter rows (Region = North & Amount > 200)
print(transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)])

# Value counts for ProductCategory
print(transactions['ProductCategory'].value_counts())

# Unique values in Region
print(transactions['Region'].unique())

# Group by Region → mean Amount
print(transactions.groupby('Region')['Amount'].mean())


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West 

In [15]:
#3. Manipulating the DataFrame
# Modify Amount for TransactionID 102 → 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print(transactions)

# Add Discount column (10% of Amount)
transactions['Discount'] = transactions['Amount'] * 0.10
print(transactions)

# Remove row with TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]
print(transactions)

# Delete Discount column
transactions = transactions.drop(columns=['Discount'])
print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7       